mycloudnexus/vortex

vortex-app/vortex-app-api/src/main/resources/application.yaml
vortex-app/vortex-app-api/src/test/resources/application.yml
vortex-java-sdk/vortex-java-sdk-iam/pom.xml
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/config/WebSecurityConfig.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/AuthTokenController.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/model/AuthDataProperty.java

1. add spring-security and enable oauth2-resource-server
2. Bearer token is required to access the endpoints
3. three  new envs are required for jwt token verifier
- JWT_ISSUER_URI
- JWT_JWK_SET_URI
- JWT_AUDIENCES

feat(sdk): integrate with spring security and enable oauth2 config

---

vortex-app/vortex-app-api/src/main/resources/application.yaml
vortex-java-sdk/vortex-java-sdk-core/src/main/java/com/consoleconnect/vortex/core/model/Email.java
vortex-java-sdk/vortex-java-sdk-iam/pom.xml
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/model/EmailProperty.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/model/IamProperty.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/EmailService.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java

Add sendgrid-java sdk to support email service.

feat(sdk): add senggrid-java sdk

---

vortex-app/vortex-app-api/src/main/resources/application.yaml
vortex-java-sdk/vortex-java-sdk-gateway/pom.xml
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/filter/SetAPIKeyGatewayFilterFactory.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/config/WebSecurityConfig.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/filter/JWTSecurityGlobalFilter.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/model/Auth0Property.java

add spring-cloud-gateway into the api server and via spring.cloud.gateway configuration can forward the API request to downstream API Server

feat(sdk): add spring cloud gateway to forward request to downstream api server

---

.github/CODEOWNERS

Add a github codeowners, plan to enable `Require review from Code Owners` for pull request.

build(misc): add github codeowners

---

vortex-e2e/.mvn/wrapper/maven-wrapper.properties
vortex-e2e/mvnw
vortex-e2e/mvnw.cmd
vortex-e2e/pom.xml
vortex-e2e/vortex-e2e-app-api/.mvn/wrapper/maven-wrapper.properties
vortex-e2e/vortex-e2e-app-api/README.md
vortex-e2e/vortex-e2e-app-api/mvnw
vortex-e2e/vortex-e2e-app-api/mvnw.cmd
vortex-e2e/vortex-e2e-app-api/pom.xml
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/E2ETest.java
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/user/UserRunner.java
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/user/user.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/karate-config.js
vortex-e2e/vortex-e2e-app-api/src/test/java/logback-test.xml

Add a new module: vortex-e2e-app-api for API server end-2-end test.

feat(sdk): add e2e test module

---

vortex-e2e/vortex-e2e-app-api/pom.xml
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/organization/organization.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/user/user.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/karate-config.js
vortex-e2e/vortex-e2e-app-api/src/test/resources/data/create_organization.json
vortex-e2e/vortex-e2e-app-api/src/test/resources/schemas/organization-schema.json
vortex-e2e/vortex-e2e-app-api/src/test/resources/schemas/user-schema.json

Add some test cases for organization API and user API.
#27 
Add automation testing to improve testing eddiciency and maintain code stability.
* All tests were executed locally and passed successfully.

test(misc): add tests for organization API and user API

---

vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/UserOrganizationController.java

Removing @PreAuthorize from organization APIs, which leads to incorrect access control.
@PreAuthorize was originally used for permission-based control, and it should be removed now that role-based control is used.
This change solved the 500 error when calling organization/* API.
I've tested it locally, and the issue is resolved.

fix(sdk): remove permission based control for organization APIs

---

.github/workflows/ci.yaml
pom.xml
sonar-project.properties
vortex-e2e/pom.xml

As this repo contains java code and nodejs code, so create two mono projects in sonarcloud.
one is mycloudnexus_vortex_java, another one is mycloudnexus_vortex_nodejs.
Then will generate two sonar-cloud scan repo this each PR, one for java and another one for nodejs.

build(misc):  integrate with sonar-cloud for code scan

---

vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/filter/ResponseAdapterGatewayFilterFactory.java

fix(sdk): filter sorted

---

vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/MgmtOrganizationController.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/CreateConnectionDto.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/OidcConnection.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/OidcConnectionDto.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/SamlConnection.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/SamlConnectionDto.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/UpdateConnectionDto.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/connection/AbstractConnection.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/connection/OIDCConnection.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/connection/SAMLConnection.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/connection/UsernamePasswordConnection.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/service/OrganizationServiceTest.java

1. Extract abstract connection using template pattern.
2. Add username-password connection

feat(sdk): extract abstract connection and add username-password connection

---

vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/OrganizationMetadata.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/connection/AbstractConnection.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/connection/SAMLConnection.java

1. Fix the SAML connection logic when updating the SAML connection.
2. Fix the organization login type when updating the status.

fix(sdk): fix organization/saml-connection updating logic.

---

vortex-app/vortex-app-portal/src/components/Access/Authenticate.tsx

show error message if auth0 have  login error

fix(portal):  show auth0  error message

---

vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/adapter/RouteAdapterContext.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/adapter/RouteAdapterFactory.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/adapter/cc/AbstractAdapter.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/adapter/cc/DefaultResourceListAdapter.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/adapter/cc/DefaultResourceOrderCreateAdapter.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/config/ApiProperty.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/config/RouteAdapterProperty.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/repo/OrderRepository.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/service/OrderService.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/toolkit/JsonPathToolkit.java
vortex-java-sdk/vortex-java-sdk-gateway/src/test/java/com/consoleconnect/vortex/gateway/adapter/ResponseAdapterTest.java
vortex-java-sdk/vortex-java-sdk-gateway/src/test/resources/application.yaml

1. add general properties for the adapter config;
```
response-root-path: for parsing the response body of different APIs
```  
2. define default resource(port, L2 ...) list adapter class (DefaultResourceListAdapter)

feat(sdk): define default resource list adapter

---

vortex-app/vortex-app-portal/src/components/Access/__test__/Authenticate.test.tsx

update `Authenticate.test.tsx` file fix  test waiting error

fix(portal): update test file

---

vortex-app/vortex-app-portal/package-lock.json
vortex-app/vortex-app-portal/package.json

fix Library Vulnerability scan results as follows
Library | Vulnerable version | Severity | Fix version | Vulnerability ID
-- | -- | -- | -- | --
@eslint/plugin-kit | 0.2.1 | High 🟡 | 0.2.3 | GHSA-7q7g-4xm8-89cq
cross-spawn | 7.0.3 | High 🟡 | 7.0.5 | GHSA-3xgq-45jj-v275
Library	Vulnerable version	Severity	Fix version	Vulnerability ID
@eslint/plugin-kit	0.2.1	High 🟡	0.2.3	[GHSA-7q7g-4xm8-89cq](https://github.com/advisories/GHSA-7q7g-4xm8-89cq)
cross-spawn	7.0.3	High 🟡	7.0.5	[GHSA-3xgq-45jj-v275](https://github.com/advisories/GHSA-3xgq-45jj-v275)

fix(portal): lib issue

---

vortex-app/vortex-app-api/src/main/resources/db/migration/V1__init.sql

update table column resource_type check

fix(sdk): update table column resource_type check

---

vortex-e2e/vortex-e2e-app-api/src/main/java/com/consoleconnect/vortext/toolkit/deep-merge.js
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/organization/invitation.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/organization/member.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/organization/mgmt-connection.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/organization/mgmt-organization.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/organization/mgmt-role.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/user/mgmt-user.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/com/consoleconnect/vortex/e2e/user/user.feature
vortex-e2e/vortex-e2e-app-api/src/test/java/karate-config.js
vortex-e2e/vortex-e2e-app-api/src/test/resources/data/organization/create_invitation.json
vortex-e2e/vortex-e2e-app-api/src/test/resources/data/user/add_user.json
vortex-e2e/vortex-e2e-app-api/src/test/resources/schemas/member-schema.json
vortex-e2e/vortex-e2e-app-api/src/test/resources/schemas/reseller-user-schema.json
vortex-e2e/vortex-e2e-app-api/src/test/resources/schemas/user-schema.json

Some cases failed after code changes. Update them to align with the latest API changes.
Run tests locally, all tests passed.

test(api): fix the failed e2e test cases

---

vortex-app/vortex-app-api/src/main/resources/application.yaml
vortex-app/vortex-app-api/src/test/java/com/consoleconnect/vortex/AppTest.java
vortex-app/vortex-app-api/src/test/java/com/consoleconnect/vortex/DownstreamAPITest.java
vortex-app/vortex-app-api/src/test/resources/application.yml
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/acl/JwtAuthenticationManager.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/controller/MgmtUserControllerTest.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/application.yaml

for mgmt users, if it's not invited, then response 403, FE can handle this case based on the 403 code.

feat(sdk): response 403 for uninvited users

---

vortex-app/vortex-app-api/src/main/resources/application.yaml
vortex-java-sdk/vortex-java-sdk-core/src/main/java/com/consoleconnect/vortex/core/config/AppConfig.java
vortex-java-sdk/vortex-java-sdk-core/src/main/java/com/consoleconnect/vortex/core/model/AppProperty.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/config/IamConfig.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/model/EmailProperty.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/model/IamProperty.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/EmailService.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/UserService.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/config/EmailServiceMockHelper.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/controller/MgmtUserControllerTest.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/controller/OrganizationControllerTest.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/service/EmailServiceTest.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/application.yaml

1. Send email when inviting reseller users.
2. Add the connection filter when getting users from Auth0.

feat(sdk): send email when inviting reseller users

---

vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java

1. Fix the pagination issue of the organization list.
2. Checking before deleting a connection.
3. Fix the member list issue.

fix(sdk): fix the pagination issue of organization list.

---

vortex-app/vortex-app-portal/src/pages/Settings/CustomerCompany/__test__/CustomerCompany.test.tsx
vortex-app/vortex-app-portal/src/pages/Settings/CustomerCompany/index.tsx
vortex-app/vortex-app-portal/src/services/types.ts

* add integration customer status update
We need to integrate the API to process the update
Tested on local

feat(portal): update status integration

---

.github/workflows/ci.yaml
docker/app-portal/Dockerfile

.babelrc has been deleted in https://github.com/mycloudnexus/vortex/pull/86

build(misc): fix docker build failed

---

.github/workflows/ci.yaml

improve the CI workflow, only run nodejs unit test on files changed under:
- vortex-app/vortex-app-portal/
- docker/app-portal/

build(misc): run nodejs test only on folder changed

---

vortex-app/vortex-app-portal/src/components/Layout/__test__/__snapshots__/index.test.tsx.snap
vortex-app/vortex-app-portal/src/components/Layout/index.tsx
vortex-app/vortex-app-portal/src/pages/Settings/CustomerCompany/index.tsx
vortex-app/vortex-app-portal/src/routers/index.tsx

* Update breadcrumb label of Customer
Align with the updated UI
Test in local

fix(portal): breadcrumb

---

vortex-app/vortex-app-api/src/main/resources/application.yaml
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/transformer/AbstractTransformer.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/transformer/ListModifyTransformer.java
vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/transformer/TransformerChain.java
vortex-java-sdk/vortex-java-sdk-gateway/src/test/java/com/consoleconnect/vortex/gateway/DownstreamAPIControllerTest.java
vortex-java-sdk/vortex-java-sdk-gateway/src/test/resources/application-auth-hs256.yaml
vortex-java-sdk/vortex-java-sdk-gateway/src/test/resources/consoleconnect/get_api_company_{companyName}_ports_{portId}_connections.json

use the default value when reading a existing json path in the ListModifyTransformer class

feat(sdk): list modify transformer support default value

---

vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/filter/ResponseBodyTransformerGatewayFilterFactory.java
vortex-java-sdk/vortex-java-sdk-gateway/src/test/java/com/consoleconnect/vortex/gateway/DownstreamAPIControllerTest.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/filter/UserContextWebFilter.java

fix bugs：
if reseller user login vortex and add the header x-vortex-customer-id which value is the same as reseller company id cause the CustomerType wrong
**Check list**: [PR-111](https://docs.google.com/spreadsheets/d/1l5kualdga8rnDOpJzQAYHmBFOQyxjPIx/edit?gid=381706354#gid=381706354)

fix(sdk): ensure that the CustomerType  is right

---

vortex-java-sdk/vortex-java-sdk-gateway/src/main/java/com/consoleconnect/vortex/gateway/filter/ResponseBodyTransformerGatewayFilterFactory.java

fix fetch the response body is blocked
**Check list**: [pr-115](https://docs.google.com/spreadsheets/d/1l5kualdga8rnDOpJzQAYHmBFOQyxjPIx/edit?gid=715567421#gid=715567421)

fix(sdk): fix fetch the response body is blocked

---

vortex-app/vortex-app-api/src/main/resources/application.yaml
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/controller/OrganizationController.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/dto/UserSignupDto.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/OrganizationService.java
vortex-java-sdk/vortex-java-sdk-iam/src/main/java/com/consoleconnect/vortex/iam/service/connection/AbstractConnectionProvider.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/java/com/consoleconnect/vortex/iam/controller/OrganizationControllerTest.java
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/inactive_organization/get_api_v2_organizations_{id}.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/inactive_organization/index.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/success/get_api_v2_connections_{id}.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/success/get_api_v2_organizations.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/success/get_api_v2_organizations_{id}.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/success/get_api_v2_organizations_{id}_invitations_{invitationId}.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/success/index.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/success/post_api_v2_organizations_{id}_members.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/success/post_api_v2_organizations_{id}_members_{memberId}_roles.json
vortex-java-sdk/vortex-java-sdk-iam/src/test/resources/auth0/signup/success/post_api_v2_users.json

- Sign up through the invitation link.[POPING-3447](https://jira.pccwglobal.com/browse/POPING-3447)
> This commit: ed3ae2b57ab29558439fecf53a5a12421aa6f245 are all for unit test.
> This commit: f3069ac5a718f98624e10fb1902cfa9b1215cf36 is for functionality.
- Allow access to downstream pictures.
Click [here](https://docs.google.com/spreadsheets/d/1lFb7c9JRq5mHDEHqsXnON_dlsO7Wvb8A/edit?gid=1674700015#gid=1674700015).

feat(sdk): sign up through the invitation link
